
 <!-- Aquí puedes mostrar la lista de tareas  -->
 <!-- iterar sobre las tareas y mostrarlas en la página: -->

<main class="flex mt-2">
      <!-- Layout a la izqda -->
      <aside class="w-1/4 px-6 bg-black-500 ">
        <div class="ml-5">
          <h2 class="text-white text-5xl font-bold mb-2 ">Views</h2>
          <hr class="my-8 border-t-2 border-white-400"style="width: 100%;">
          <p class="text-white text-black-600 text-lg font-semibold">
            Choose a filter to see results
          </p>
        </div>

        <div class="mt-6 ml-5 ">
          <h3 class="text-white text-3xl font-bold mb-2 ">Frequency</h3>
          <hr class="my-4 border-t-2 border-white-400"style="width: 100%;">
          <ul class="list-none ml-4 text-white">
            <li class="font-sans hover:font-serif text-lg font-semibold mt-6 hover:text-blue-300">Weekly</li>
            <li class="font-sans hover:font-serif text-lg font-semibold mt-6 hover:text-blue-300">Monthly</li>
            <li class="font-sans hover:font-serif text-lg font-semibold mt-6 hover:text-blue-300">Yearly</li>
          </ul>
        </div>
        <div class="mt-6 ml-5">
          <h3 class="text-white text-3xl font-bold mb-2">State</h3>
          <hr class="my-4 border-t-2 border-white-400"style="width: 100%;">
          <ul class="list-none ml-4 text-white">
            <li class="font-sans hover:font-serif text-lg font-semibold mt-6 hover:text-blue-300">Pending</li>
            <li class="font-sans hover:font-serif text-lg font-semibold mt-6 hover:text-blue-300">Ongoing</li>
            <li class="font-sans hover:font-serif text-lg font-semibold mt-6 hover:text-blue-300">Completed</li>
          </ul>
        </div>
      </aside>
      

