<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <script src="https://cdn.tailwindcss.com"></script>
  <script src="https://kit.fontawesome.com/35a2d9730b.js" crossorigin="anonymous"></script>
  <title>To-Do_List</title>
</head>

<body class="bg-slate-600">
  <header>
    <!-- <div class="relative h-96">
      //!NO FUNCIONA
      <div class="header-image">
        <img class="w-full h-auto" src="/web/images/videoHeader/Agenda.png" alt="Agenda en Letras">
      </div> -->
    <!-- <div class="header-video">
      //!DE MOMENTO NO FUNCIONA
      <video autoplay loop muted class="absolute inset-0 w-full h-full object-cover z-0 " id="background-video">
        <source src="/web/images/videoHeader/To-Do_List.mp4" type="video/mp4">
      </video>
      <h1 class=text-white>To-Do List</h1>
    </div> -->
  </header>