<div class="flex justify-center items-center h-screen">
    <div class="bg-white p-8 rounded-lg shadow-lg w-96">
        <h1 class="text-2xl font-semibold mb-4">Editar Tarea</h1>

        <form method="post" action="updateTask">
            <!-- Input invisible para almacenar el id -->
            <input type="hidden" name="taskId" value="<?= $this->taskToEdit['id'] ?>">

            <div class="mb-4">
                <label for="taskDescription" class="block mb-1">Descripción de la Tarea:</label>
                <input type="text" name="taskDescription" id="taskDescription" value="<?= $this->taskToEdit['task_description'] ?>" class="w-full border rounded py-2 px-3">
            </div>

            <div class="mb-4">
                <label for="author" class="block mb-1">Autor:</label>
                <input type="text" name="author" id="author" value="<?= $this->taskToEdit['author'] ?>" class="w-full border rounded py-2 px-3">
            </div>

            <div class="mb-4">
                <label for="startingDate" class="block mb-1">Fecha de Inicio:</label>
                <input type="date" name="startingDate" id="startingDate" value="<?= $this->taskToEdit['starting_date'] ?>" class="w-full border rounded py-2 px-3">
            </div>

            <div class="mb-4">
                <label for="endDate" class="block mb-1">Fecha de Finalización:</label>
                <input type="date" name="endDate" id="endDate" value="<?= $this->taskToEdit['end_date'] ?>" class="w-full border rounded py-2 px-3">
            </div>

            <div class="mb-4">
                <label for="status" class="block mb-1">Estado:</label>
                <select name="status" id="status" class="w-full border rounded py-2 px-3">
                    <option value="Pending" <?= ($this->taskToEdit['status'] === 'Pending') ? 'selected' : '' ?>>Pending</option>
                    <option value="Ongoing" <?= ($this->taskToEdit['status'] === 'Ongoing') ? 'selected' : '' ?>>Ongoing</option>
                    <option value="Completed" <?= ($this->taskToEdit['status'] === 'Completed') ? 'selected' : '' ?>>Completed</option>
                </select>
            </div>

            <!-- Botón para guardar los cambios centrado -->
            <div class="text-center">
                <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded">Guardar Cambios</button>
            </div>
        </form>
    </div>
</div>
