<?php 

//$url = $this->baseUrl();
$dataJ = $this->dataJ;
//? comprobamos si la variable está definida
if (isset($dataJ)) : ?>
 
      <!-- Mostramos los datos en una tabla  -->
    <table style='border:1'>
        <thead>
            <tr>
                <th>Descripción de la Tarea</th>
                <th>Autor</th>
                <th>Fecha de Inicio</th>
                <th>Fecha de Finalización</th>
                <th>Estado</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($dataJ as $task) : ?>
                <tr>
                    <td><?php echo $task['task_description']; ?></td>
                    <td><?php echo $task['author']; ?></td>
                    <td><?php echo $task['starting_date']; ?></td>
                    <td><?php echo $task['end_date']; ?></td>
                    <td><?php echo $task['status']; ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php else : ?>
    <!-- Cuando $dataJ no está disponible -->
    <p>Archivo no disponible.</p>
<?php endif; ?>