<?php

$dataJ = $this->dataJ;
// Comprobamos si la variable está definida para poder mostrar los datos
if (isset($dataJ)) : ?>

<!-- Mostramos los datos en una tabla  -->
    <table style='border:1'>
        <thead>
            <tr>
                <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Descripción de la Tarea</th>
                <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Autor</th>
                <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Fecha de Inicio</th>
                <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Fecha de Finalización</th>
                <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Estado</th>
            </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
            <?php
            
                // Get the current date
                $currentDate = new DateTime();
            
                foreach ($dataJ as $task) : 

                // Parse the task dates in 'yyyy-mm-dd' format
                $startDate = DateTime::createFromFormat('Y-m-d', $task['starting_date']);
                $endDate = DateTime::createFromFormat('Y-m-d', $task['end_date']);

                // Calculate the difference in days between the start date and current date
                $dateDifference = $startDate->diff($currentDate)->format('%a');
            
                if ($dateDifference == 0 && $dateDifference <= 6) : ?>

                <tr>

                    <td class="px-6 py-4 whitespace-no-wrap" ><?php echo $task['task_description']; ?></td>
                    <td class="px-6 py-4 whitespace-no-wrap"><?php echo $task['author']; ?></td>
                    <td class="px-6 py-4 whitespace-no-wrap"><?php echo $startDate->format('d/m/Y'); ?></td>
                    <td class="px-6 py-4 whitespace-no-wrap"><?php echo $endDate->format('d/m/Y'); ?></td>
                    <td class="px-6 py-4 whitespace-no-wrap"><?php echo $task['status']; ?></td>

                    <!-- Completar descripción de la función form-->
                    <!-- Pero vamos que me lleva a: ediTask.phtml cogiendo el id de la tarea -->
                    <td>
                        <form method="post" action="ediTask">
                            <input type="hidden" name="taskId" value="<?php echo $task['id']; ?>">
                            <!-- el echo de ↑↑ no sé exactamente pq pero si lo quito no almacena el id... -->
                            <button class="bg-slate-50 w-full mt-3 md:mt-0 h-10 py-4 px-1 md:py-0 md:px-2 rounded hover:bg-blue-300" style="margin-top:-10px;" type="submit" name="buttonEditTask">
                                <i class="fa-solid fa-pencil"></i>
                            </button>
                        </form>
                    </td></i>
                    </button>
                    </td>
                    <td>
                        <form method="post" action="deleteTask">
                            <input type="hidden" name="taskId" value="<?php echo $task['id']; ?>">
                        <button class="bg-slate-50 w-full mt-3 md:mt-0 h-10 py-4 px-1 md:py-0 md:px-2 rounded hover:bg-blue-300" style="margin-top:-10px;" type="submit" name="">
                            <i class="fa-solid fa-trash"></i>
                        </button>
                        </form>
                    </td>

                </tr>
                <?php endif;
        endforeach;
        ?>
    </tbody>
</table>
<?php else : ?>
    <!-- Cuando $dataJ no está disponible -->
    <p>Archivo no disponible.</p>
<?php endif; ?>