

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<script src="https://cdn.tailwindcss.com"></script>
	<script src="https://kit.fontawesome.com/35a2d9730b.js" crossorigin="anonymous"></script>
	<title>To-Do_List</title>
</head>

<body class="bg-slate-600">
	<header style='height: 100px;'>
		<div></div>
		<div><h1>AQUÍ IRÁ EL CONTENIDO DEL HEADER</h1></div>
	</header>
	<main class="flex-grow">
	

         <!-- Other content in the main section -->
        <?= $this->content() ?>
    </main>
	<footer></footer>
</body>

</html>


